title:
  en: "The Cube: El Jueguito"
  es: "The Cube: El Jueguito"
finished: finished
descriptionShort:
  en: "The Cube, also known as El Jueguito, was my first major programming project. With the aim of learning C# and Unity, I started this game as a practice project. The concept is simple: protect a cube from enemies. Round after round, more and more enemies appear, each stronger than the previous. When you can no longer hold them back, you can use the money to upgrade your weapons and survive further rounds!"
  es: "The Cube, también conocido como El Jueguito, fue mi primer proyecto 'grande' de programación. Lo empecé para aprender C# y Unity (gráficos incluidos, hechos por mi). La idea es sencilla: proteger un cubo de los enemigos. Cada ronda aparecen más y más, y cuando no puedas resistir más, puedes gastar el dinero que ganas en mejorar tu personaje para seguir sobreviviendo."
descriptionLong:
  en: |
    The Cube, also known as El Jueguito, was my first major programming project. With the aim of learning C# and Unity, I started this game as a practice project. Creating the visuals and assets using Photoshop resulted in a visually appealing game. The concept is simple: protect a cube from enemies. Round after round, more and more enemies appear, each stronger than the previous, and sometimes they come with a surprise. Defeating each enemy rewards you with money. When you can no longer hold them back, you can use the money to upgrade your weapons and survive further rounds!
  es: |
    The Cube, o El Jueguito, fue mi primer proyecto 'grande' de programación. Lo empecé con el objetivo de aprender C# y Unity. También hice los gráficos y assets en Photoshop, lo que le dio un buen acabado visual. La mecánica es sencilla: tienes que defender un cubo de oleadas de enemigos, que se vuelven más fuertes con cada ronda. Al derrotarlos ganas dinero, que puedes invertir en mejorar tus weapons para aguantar más tiempo.
technologies: [c-sharp, unity, photoshop]
tags: [personal]
logo: readme_images/El jueguito (1).webp
screenShoots:
  - readme_images/El jueguito (1).webp
  - readme_images/El jueguito (2).webp
  - readme_images/El jueguito (3).webp
  - readme_images/El jueguito (4).webp
  - readme_images/El jueguito (5).webp
  - readme_images/El jueguito (6).webp
  - readme_images/El jueguito (7).webp
youtube: J6wj_w_J8AU
keywords:
  en: [tower defense, wave survival, Unity game, enemy waves, money upgrade, pixel art, itch.io, game development, C# game, casual game, first big project, rounds]
  es: [tower defense, supervivencia por oleadas, juego Unity, oleadas de enemigos, mejoras con dinero, pixel art, itch.io, desarrollo de juegos, juego C#, juego casual, primer proyecto grande, rondas]
slug: The-Cube-ElJueguito
order: 70
featured: false

